site_name: NeoCargo
site_description: Plataforma inteligente de simulação e alocação de veículos para transporte de cargas
site_author: NeoCargo Team
site_url: https://transportadora-django.github.io/Documentacao

# Repository
repo_name: Transportadora-Django/Documentacao
repo_url: https://github.com/Transportadora-Django/Documentacao
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  language: pt-BR
  logo: assets/Logo-NeoCargo.svg
  favicon: assets/Logo-NeoCargo.svg
  
  # Custom colors
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - toc.follow
    - toc.integrate

# Plugins
plugins:
  - search:
      lang: pt
  - git-revision-date-localized:
      locale: pt_BR
      type: datetime
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: Transportadora-Django
      repo: Documentacao
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Navigation
nav:
  - Home: index.md
  - Brainstorm: 04-brainstorm-historias.md
  - Backlog: 05-backlog.md
  - UML Planejado: 06-uml-geral.md
  - UML Implementado: 08-uml-implementado.md
  - Banco de Dados: 07-banco-dados.md

# Extra
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/johnnylopes/TPPE-2025.2
    - icon: fontawesome/solid/envelope
      link: mailto:contato@neocargo.com
  
  generator: false

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Custom JavaScript
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js